services:
  app:
    build: .
    container_name: minili
    restart: always
    image: minili:2.0.0
    environment:
      - PORT=3000
      - APP_URL=${APP_URL}
      - MONGO_URI=${MONGO_URI}
      - REDIS_URL=${REDIS_URL}

    networks:
      - web
      - backend-network

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      # Router (HTTP)
      - "traefik.http.routers.minili.rule=Host(`minili.ismaelrakoto.com`)"
      - "traefik.http.routers.minili.entrypoints=websecure"
      - "traefik.http.routers.minili.tls.certresolver=leresolver"

      # Service port inside container
      - "traefik.http.services.minili.loadbalancer.server.port=3000"

networks:
  web:
    external: true
  backend-network:
    external: true
